version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: noc123
    volumes:
      - grafana_data:/var/lib/grafana

  telegraf:
    image: telegraf:latest
    depends_on:
      - prometheus
    volumes:
      - ./telemetry/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "9273:9273"

volumes:
  grafana_data:
