[agent]
  interval = "30s"
  flush_interval = "30s"

[[inputs.ping]]
  urls = ["10.0.1.2", "10.0.2.2", "10.0.3.2"]
  count = 3
  ping_interval = 1.0

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
